version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bench
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  default:
    driver: bridge
